spring:
  application:
    name: DOCTOR-SERVICE
  spring:


#
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/yourDatabase




  profiles:
    active: dev


    # Other properties related to MongoDB can be added here



server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
